// Autogenerated from sqlalchemy.template file
class Address {

    protected String street;
    protected String city;
    protected String country;

    public String getStreet() {
        return this.street;
    }

    public void setStreet(String new_value) {
        this.street = new_value;
    }

    public String getCity() {
        return this.city;
    }

    public void setCity(String new_value) {
        this.city = new_value;
    }

    public String getCountry() {
        return this.country;
    }

    public void setCountry(String new_value) {
        this.country = new_value;
    }


}