// Autogenerated from sqlalchemy.template file
class ExperimentRun {


  protected String name;


  protected String notes;


  protected Experiment experiment;


  protected List<Group> groups;  // 

  protected List<Result> result;  // 

  public String getName(){
    return this.name;
  }

  public void setName(String new_value){
    this.name = new_value;
  }

  public String getNotes(){
    return this.notes;
  }

  public void setNotes(String new_value){
    this.notes = new_value;
  }

  public Experiment getExperiment(){
    return this.experiment;
  }

  public void setExperiment(Experiment new_value){
    this.experiment = new_value;
  }

  public Group getGroups(){
    return this.groups;
  }

  public void setGroups(Group new_value){
    this.groups = new_value;
  }

  public Result getResult(){
    return this.result;
  }

  public void setResult(Result new_value){
    this.result = new_value;
  }


}