// Autogenerated from java.template file
class Group {


  protected String name;


  public String getName(){
    return this.name;
  }

  public void setName(String new_value){
    this.name = new_value;
  }


}