// Autogenerated from sqlalchemy.template file
class Person {

  protected String name;
  protected Address address;
  protected int age;
  protected String gender;

  public String getName(){
    return this.name;
  }

  public void setName(String new_value){
    this.name = new_value;
  }

  public Address getAddress(){
    return this.address;
  }

  public void setAddress(Address new_value){
    this.address = new_value;
  }

  public int getAge(){
    return this.age;
  }

  public void setAge(int new_value){
    this.age = new_value;
  }

  public String getGender(){
    return this.gender;
  }

  public void setGender(String new_value){
    this.gender = new_value;
  }


}