// Autogenerated from java.template file
class UserGroup {


  protected Group group;


  protected User user;


  public Group getGroup(){
    return this.group;
  }

  public void setGroup(Group new_value){
    this.group = new_value;
  }

  public User getUser(){
    return this.user;
  }

  public void setUser(User new_value){
    this.user = new_value;
  }


}