// Autogenerated from java.template file
class User {


  protected String username;


  public String getUsername(){
    return this.username;
  }

  public void setUsername(String new_value){
    this.username = new_value;
  }


}